export function CodeGenerator() {
  return (
    <div className='flex flex-col text gap-[10px] bg-gray-700'>
      <div className='title'>Code Generator</div>
      <div>
        The code generator is just a processing pipeline for the .json file
        generated by swagger.
      </div>
      <div></div>
      <div className='ml-3 subtitle'>Motivation :</div>
      <p>
        The idea behind it is simple, the enums, Models and Controllers are
        already defined on the back end side. There's absolutely no reason to do
        this labour intensive, error prawn work on the front end again.
      </p>
      <p>
        I believe that any kind of repetitive work can be done much faster by a
        computer.
      </p>

      <div className='ml-3 subtitle'>Design :</div>
      <p></p>

      <div className='ml-3 subtitle'>Planned Features :</div>
      <p>
        Add support for other languages other then TypeScript. This should be
        quite easy once all the keywords are added to the configuration file.
      </p>
      <p>
        At the moment it is only capable of defining a class's attributes and
        the constructor. The ability to generate toJSON() and fromJSON() methdos
        would add a huge productivity boost to any other language other then
        TS/JS.
      </p>

      <p>Publish it as an npm package.</p>
    </div>
  )
}
